### ISSUE TITLE
Multiple builds (ARM + ARM64)

### ISSUE THREAD

**Issue by renandecarlo** [MBuchalik/cordova-build-architecture#11]
Is there any way to make it work with multiple builds such as arm + arm64, instead of just one? 
Something like `<preference name="buildArchitecture" value="arm,arm64" />`, or maybe `<preference name="buildArchitecture" value="arm64,x86_64" />`

**Comment by MBuchalik** [comment]
Just to make sure I understood your question correctly: You want to get one .apk file that, for instance, contains both the 32 and 64 bit version of your app?

I assume you are using Crosswalk. I haven't yet heard of an option to generate one combined 32 and 64 bit version. Maybe, there is an option; but I cannot remember having seen somehting like this. 🙁 

On the other hand: Why would you create one combined 32 and 64 bit version of your app? If you are using Crosswalk, this will make your .apk file really huge.


> or maybe `<preference name="buildArchitecture" value="arm64,x86_64" />`

This should actually be possible in Crosswalk. Just remove (!) my plugin and add this to `config.xml` (not tested!) : 

``` xml
<preference name="xwalk64bit" value="true" />
<preference name="xwalkMultipleApk" value="false" />
```

**Comment by renandecarlo** [comment]
@MBuchalik, actually, I want two different apks. One ARM64bit, and one ARM32bit. Currently, with your plugin it makes just one of these at a time, and without it it makes either ARM32bit and x86 or just the 64bit for both.
I am using Crosswalk.

Is it possible?

> This should actually be possible in Crosswalk. Just remove (!) my plugin and add this to `config.xml` (not tested!) :

This is possible. I just mentioned it as an example. My bad.

**Comment by MBuchalik** [comment]
@renandecarlo OK so you want to make Crosswalk generate the 32 and 64 bit apk files with one build. 

Unfortunately, my plugin can't help you at this point. It simply serves a different purpose.

I assume you will need to edit the Crosswalk Cordova plugin. I have read through some files and probably have an idea where to start:
(Please note that I have only little experience with gradle, so I might be completely mistaken.)
Create a fork of https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview

In this fork, open the file https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/blob/master/platforms/android/xwalk.gradle

Find the if clause looking like this:

```
if (xwalk64bit != null) {
   productFlavors {
        ....
   }
}
```
and just remove it and all the content.

Also, remove

```
if (xwalk64bit != null) {
        xwalkSpec = xwalkSpec + BIT_64
}
```

Now, it gets tricky. This is where my knowledge regarding gradle ends. Have a look at

```
dependencies {
        implementation xwalkSpec
}
```

What we probably want is:

```
dependencies {
        implementation xwalkSpec
        implementation xwalkSpec + BIT_64
}
```

However, I don't know if this won't include both the 32 and 64 bit library in one single .apk file. This would be bad. So: We need to find a way to limit the `implementation`  declaration somehow. Unfortunately, I don't know how. I read some articles about this and maybe, just maybe, something like this could work:

```
dependencies {
        armv7Implementation xwalkSpec
        arm64Implementation xwalkSpec + BIT_64
}
```


Going to close this issue since my plugin can't help at this point. However, it would be nice if you could report whether you found a solution. 😃

**Comment by againer** [comment]
Okay, I know this is closed. But I figured I would add some insights here (hopefully useful).  I ended up forking `cordova-plugin-crosswalk-webview` and updating `xwalk.gradle`'s `android` section:
```
android {

      defaultConfig.ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
        
      flavorDimensions "default"
      productFlavors {
        thirtytwo {
            ndk {
              abiFilters "armeabi-v7a", "x86", ""
            }
        }
        sixtyfour {
            ndk {
              abiFilters "arm64-v8a", "x86_64", ""
            }
        }
      }
 }
```
Then I removed: 
```
if (xwalk64bit != null) {
        xwalkSpec = xwalkSpec + BIT_64
}
```
added:
```
def xwalk64Spec = xwalkSpec + BIT_64
```
and updated `dependencies`:
```
 dependencies {
     thirtytwoImplementation xwalkSpec
     sixtyfourImplementation xwalk64Spec
}
```
See https://developer.android.com/studio/build/build-variants.html#dependencies. Your `productFlavors` names have to align with your calls to `implementation`.  Under your `apk` directory in your build output, you will see `thirtytwo` and `sixtyfour` and etc.

**Comment by MBuchalik** [comment]
Thanks for sharing this guide! I am sure it will help some Crosswalk users. 😃
