### ISSUE TITLE
plugin releases via npm v1.0.6 !== cordova v1.0.4

### ISSUE THREAD

**Issue by WuglyakBolgoink** [MBuchalik/cordova-build-architecture#13]
Hi!

via npm I don't see any changes for android v7+... can you synchronize repos/releases?

**Comment by WuglyakBolgoink** [comment]
with `cordova plugins add https://github.com/MBuchalik/cordova-build-architecture --save` I see changes :)

**Comment by MBuchalik** [comment]
Unfortunately, I am not the maintainer of the NPM repo. Because of this, you should fetch the plugin from git in order to get the latest changes.

I removed the link to the NPM package in 28e0237fb673017690cbca9867c5b52575611492 since it does not get regular updates and has wrong version numbers, leading to confusion among users of my plugin.


*I am closing this issue since I hope to have answered your question. If not, feel free to comment on this issue or to create a new one.*
